on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


name: Build update.xml

jobs:
  build:
    name: Building update.xml 
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Checkout code and build update.xml
        uses: actions/checkout@v3
        run: |
          cd src
          python build_update.xml.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dontpanic.update.xml
          git commit -m "Auto-Update update.xml"
          git push
  
